baseURL = "/"
languageCode = "en-us"

#theme = "hyde"
theme = "m10c"

[params]
  avatar = "avatar.png"

description = " "
# homepage = "https://blog.marcelwidmer.org"


[[params.social]]
  name = "github"
  url = "https://github.com/marzelwidmer"

[params.style]
  lightestColor = "#f5f5f5"
  primaryColor = "#0fae0d"
