---
baseURL: https://blog.marcelwidmer.org
languageCode: en-us
title: c3smonkey's blog
theme: piko
paginate: "9"
#copyright: A template by [Heksagon](https://www.heksagon.net "Your most friendly developer")
googleAnalytics: # Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: true
buildFuture: true
buildExpired: true
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: Marcel Widmer
  description:
  math: false
  images:
  - "/static"
  label:
    title: _c3smonkey's blog_
    text: Welcome to my blog
    icon: /static/favicon.ico
    iconHeight: "35"
    iconWIdth: "35"
  comments: true
  mainSections:
  - blog
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: # Get link from https://formsubmit.io or https://fabform.io
  assets:
    disableFingerprinting: false
    favicon: /static/favicon.ico
    favicon16x16: /static/favicon.ico
    favicon32x32: /static/favicon.ico
    apple_touch_icon: /static/favicon.ico
    safari_pinned_tab: /static/favicon.ico
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    # Hero Section
    disableHeroSection: true
    heroUpperTitle:
    heroTitle: Marcel Widmer
    heroDescription: Lightweight theme for your every need
    heroCTAPrimaryText: Blog
    heroCTAPrimaryUrl: "/blog/"
    heroCTASecondaryText: Contact Me
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "/static/c3smonkey-w.jpeg"
    # Blog Section
    disableBlogSection: false
    blogTitle: Latest Posts
    blogDescription: This is my latest blog posts
    seeMoreText: More Posts
    # About Section
    disableAboutSection: true
    aboutTitle: About
    aboutDescription: Just something about me
    aboutImgUrl: "/uploads/self.webp"
    aboutContent: Hi guys. This is where you put something about yourself.
    # Portfolio Section
    disablePortfolioSection: true
    portfolioTitle: Portfolio
    portfolioDescription: Some of my works
    portfolio:
    - imageUrl: /uploads/portfolio-1.webp
      alt: # image alt for better SEO
      description: Portfolio One.
      websiteUrl: #
    - imageUrl: /uploads/portfolio-2.webp
      alt: # image alt for better SEO
      description: Portfolio Two.
      websiteUrl: #
    - imageUrl: /uploads/portfolio-3.webp
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: #
  # Search Options (https://fusejs.io/)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
menus:
  main: # Main Menu
  - name: Blog
    title: Blog
    pre: pen-tool
    url: "/blog"
    weight: "20"
  - name: Search
    title: Search
    pre: search
    url: "/search"
    weight: "30"
  - name: Contact
    title: Contact
    pre: mail
    url: "/contact"
    weight: "40"
  - name: Github
    title:
    pre: github
    url: https://github.com/marzelwidmer
    weight: "50"
  search: # Search page's quick links
  - name: Categories
    title: Categories
    url: "/categories"
    weight: "10"
  - name: Archives
    title: Archives
    url: "/archives"
    weight: "20"
  - name: Tags
    title: Tags
    url: "/tags"
    weight: "30"

# Enable asciidoctor
security:
  exec:
    allow : ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
    osEnv : ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]


