baseURL = "/"
languageCode = "en-us"
theme = "m10c"

#theme = "indigo"
#theme = "lithium"
#theme = "hello-friend-ng"

[params]
  avatar = "avatar.png"

description = "This is my personal blog where I will mostly post about development."
# homepage = "https://blog.marcelwidmer.org"


[[params.social]]
  name = "github"
  url = "https://github.com/marzelwidmer"

[params.style]
  # darkestColor = "#d35050"
  # darkColor = "#212121"
  # lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#0fae0d"
#  subTitleColor = "#9B8A0F"
#  titleColor =  "#9B8A0F"
