baseURL = "https://blog.marcelwidmer.org"
languageCode = "en-us"
title = "c3smonkey's blog"
# title = "c3smonkey.ch"
#theme = "kraiklyn"
# theme = "indigo"
 theme = "simplog"

[params]
avatar = "avatar.png"

description = "This is my personal blog where I will mostly post about development."
# homepage = "https://blog.marcelwidmer.org"


[[params.social]]
name = "github"
url = "https://github.com/marzelwidmer"


[menu]

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 30
